apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 2
  selector:
      matchLabels:
        app: hello-app  
  template:
    metadata:
      labels:
        app: hello-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: hello-container
        image: ghcr.io/sayantan779/hello-world:latest
      imagePullSecrets:
      - name: ghcr-secret